import type { BroadcastSnapshot } from "@/lib/types";

export const broadcastSnapshot: BroadcastSnapshot = {
  ctfName: "HZU18 Final Round",
  dataSource: "fallback",
  phase: "prestart",
  countdownLabel: "00:18:42",
  countdownTargetUnix: null,
  ctfEndUnix: null,
  freezeLabel: "06:00:00",
  audioReady: false,
  snapshotTime: "2026-04-13 16:42 UTC+8",
  standings: [
    {
      rank: 1,
      teamId: 11,
      name: "Null Pioneers",
      score: 1640,
      delta: 500,
      solvedChallenges: 14,
      lastSolve: "00:42 ago",
      trend: "up",
      hero: {
        codename: "Photon Guard",
        role: "Vanguard",
        accent: "#2DD4BF",
      },
    },
    {
      rank: 2,
      teamId: 7,
      name: "ZeroDay Union",
      score: 1585,
      delta: 450,
      solvedChallenges: 13,
      lastSolve: "01:11 ago",
      trend: "hold",
      hero: {
        codename: "Volt Reign",
        role: "Duelist",
        accent: "#FB923C",
      },
    },
    {
      rank: 3,
      teamId: 4,
      name: "BlueFox Lab",
      score: 1490,
      delta: 350,
      solvedChallenges: 12,
      lastSolve: "03:08 ago",
      trend: "up",
      hero: {
        codename: "Nebula Thread",
        role: "Strategist",
        accent: "#A78BFA",
      },
    },
    {
      rank: 4,
      teamId: 18,
      name: "Socket Storm",
      score: 1430,
      delta: 250,
      solvedChallenges: 11,
      lastSolve: "05:16 ago",
      trend: "down",
      hero: {
        codename: "Iron Torrent",
        role: "Vanguard",
        accent: "#38BDF8",
      },
    },
    {
      rank: 5,
      teamId: 22,
      name: "Kernel Cartel",
      score: 1345,
      delta: 200,
      solvedChallenges: 10,
      lastSolve: "07:54 ago",
      trend: "hold",
      hero: {
        codename: "Crimson Relay",
        role: "Duelist",
        accent: "#F43F5E",
      },
    },
  ],
  recentEvents: [
    {
      id: "evt-1",
      type: "countdown_checkpoint",
      title: "Arena feed warmup",
      detail:
        "Starter shell is showing local mock data. Replace this list with the HZU18 SSE stream next.",
      timestamp: "Now",
      accent: "#38BDF8",
    },
    {
      id: "evt-2",
      type: "organizer_announcement",
      title: "Operator sound gate",
      detail:
        "Keep a visible Enable Sound control before the show begins to satisfy browser autoplay rules.",
      timestamp: "T-20m",
      accent: "#FB923C",
    },
    {
      id: "evt-3",
      type: "leader_changed",
      title: "Momentum callout example",
      detail:
        "Null Pioneers overtakes ZeroDay Union after a 500-point solve in the mock broadcast data.",
      timestamp: "Replay",
      accent: "#2DD4BF",
    },
  ],
  notes: [
    "Replace mock standings with GET /api/v1/hzu18/scoreboard.",
    "Add server-side fetch or a browser-safe proxy for cross-origin access to the CTF host.",
    "Wire EventSource to GET /api/v1/hzu18/events and persist the last processed event id.",
    "Swap placeholder hero codenames for your final licensed assets and sounds.",
  ],
};
